name: Astro

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Astro
        id: build
        uses: withastro/action@v3
        with:
          path: .
          node-version: 20
          package-manager: pnpm@latest

  deploy:
    name: Deploy
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages     
        id: deploy
        uses: actions/deploy-pages@v4